export const silla=[
    {nombre: 'Rosentorp', precio: 59.99, descripcion: 'Esta silla de madera de estilo tradicional con respaldo cruzado le da un encanto clásico a cualquier espacio y resulta ideal para la cocina, el salón o un dormitorio. Diseñada para combinar perfectamente con las mesas ROSENTORP.', categoria: 'Salón', imagen: 'https://www.ikea.com/es/es/images/products/rosentorp-silla-negro__1434531_pe983577_s5.jpg?f=xs'},
    {nombre: 'Stefan', precio: 35, descripcion: 'Una silla resistente de madera maciza, que se adapta a los retos del día a día. Combina con la mayor parte de los estilos y puedes completarla con un cojín para mayor comodidad.', categoria: 'Salón', imagen: 'https://www.ikea.com/es/es/images/products/stefan-silla-negro-marron-knisa-gris-beige__1068137_pe852981_s5.jpg?f=xs'},
    {nombre: 'Nordviken', precio: 69.99, descripcion: '¿Por qué esta silla resulta tan cómoda? El asiento con forma cóncava distribuye el peso de manera uniforme, el ángulo que forman el asiento y el respaldo te ayuda a mantener una buena postura y la altura del respaldo permite que tu espalda', categoria: 'Salón', imagen: 'https://www.ikea.com/es/es/images/products/nordviken-silla-negro__0714202_pe729964_s5.jpg?f=xs'},
    {nombre: 'Lisabo', precio: 49.99, descripcion: 'Un modelo de estilo artesanal tan cómodo como resistente, ideal para todas las actividades que se desarrollan alrededor de la mesa, como comer, jugar, dibujar o hacer los deberes.', categoria: 'Salón', imagen: 'https://www.ikea.com/es/es/images/products/skalsta-silla-plastico-beige-metal-tubular-negro-grisaceo__1487342_pe1002797_s5.jpg?f=xs'},
    {nombre: 'Sandsberg', precio: 12.99, descripcion: 'Ligera, amplia y apilable. Esta silla es perfecta como asiento adicional cuando tengas muchos invitados y resulta fácil de guardar para limpiar, bailar o, simplemente, tener más espacio.', categoria: 'Cocina', imagen: 'https://www.ikea.com/es/es/images/products/sandsberg-silla-blanco__1460497_pe993946_s5.jpg?f=xs'},
    {nombre: 'Vihals', precio: 20, descripcion: 'La silla VIHALS ofrece estilo, versatilidad, una calidad duradera y una gran relación calidad-precio. Esta silla, ligera y cómoda, se puede apilar para tener espacio para otras actividades. Además, el diseño sencillo permite integrarla con la decoración.', categoria: 'Cocina', imagen: 'https://www.ikea.com/es/es/images/products/vihals-silla-blanco__1414886_pe974972_s5.jpg?f=xs'},
    {nombre: 'Teodores', precio: 30, descripcion: 'Una silla cómoda, resistente, ligera y apilable. Combina fácilmente con mesas y sillas de diferentes estilos, y encaja perfectamente en el comedor, en la entrada o el dormitorio.', categoria: 'Comedor', imagen: 'https://www.ikea.com/es/es/images/products/teodores-silla-azul__1114279_pe871735_s5.jpg?f=xs'},
    {nombre: 'Skälsta', precio: 35, descripcion: '¿Buscas una silla perfecta para ti? Con la serie SKÅLSTA, puedes elegir una silla ya preparada como esta o diseñar una personalizada combinando asientos con estructuras inferiores de silla. En cualquier caso, el precio es irresistible.', categoria: 'Comedor', imagen: 'https://www.ikea.com/es/es/images/products/skalsta-silla-plastico-beige-metal-tubular-negro-grisaceo__1487342_pe1002797_s5.jpg?f=xs'},
];
export const mesa=[
    {nombre: 'Sandsberg', precio: 39, descripcion: 'Esta mesa para cuatro combina la calidez de la madera con la resistencia del metal en un diseño esbelto que luce bien incluso en espacios reducidos. Complétala con la silla SANDSBERG si quieres crear un conjunto acogedor y de aspecto homogéneo.', categoria: 'Comedor', imagen: 'https://www.ikea.com/es/es/images/products/sandsberg-mesa-negro__1074348_pe856162_s5.jpg?f=xs'},
    {nombre: 'Vihals', precio: 59, descripcion: 'La mesa VIHALS ofrece una buena relación calidad-precio y un diseño sencillo que se integra en cualquier hogar. Ideal si te gusta el diseño minimalista, así como para las familias que necesiten un mueble resistente para el día a día.', categoria: 'Dormitorio', imagen: 'https://www.ikea.com/es/es/images/products/vihals-mesa-verde-verde__1388804_pe964974_s5.jpg?f=xs'},
    {nombre: 'Näsinge', precio: 129, descripcion: 'Las mesas NÄSINGE cuenta con esquinas suaves y detalles refinados, incluidas patas biseladas y un tablero con borde, para darle un toque elegante y clásico.', categoria: 'Salon', imagen: 'https://www.ikea.com/es/es/images/products/nasinge-mesa-plegable-con-almacenaje-marron-oscuro-tinte-chapa-haya__1393640_pe966303_s5.jpg?f=xs'},
    {nombre: 'Pinntorp', precio: 99.99, descripcion: 'En esta mesa de madera se pueden sentar hasta 4 comensales cómodamente. Inspirada en los muebles suecos tradicionales, su sencillo diseño le aporta calidez y personalidad. Es la mesa perfecta para compartir momentos inolvidables con los tuyos.', categoria: 'Salon', imagen: 'https://www.ikea.com/es/es/images/products/pinntorp-mesa-tinte-marron-claro-tinte-rojo__1118108_pe872929_s5.jpg?f=xxs'},
    {nombre: 'Danderyd', precio: 199, descripcion: 'Una mesa rectangular para cuatro personas con un cuidado diseño tradicional que aúna chapa de madera y acero en una combinación de estética y resistencia concebida para la vida moderna.', categoria: 'Comedor', imagen: 'https://www.ikea.com/es/es/images/products/danderyd-mesa-hojas-abatibles-chapa-roble-blanco__1054451_pe847703_s5.jpg?f=xs'},
    {nombre: 'Väsman', precio: 179, descripcion: 'Con esta resistente mesa podrás cenar bien acompañado al aire libre. La puede abrir una persona y, como las patas siempre quedan en las esquinas, hay mucho espacio para sillas.', categoria: 'Jardin', imagen: 'https://www.ikea.com/es/es/images/products/vasman-mesa-extensible-exterior-tinte-marron-claro__1371389_pe959093_s5.jpg?f=xxs'},
    {nombre: 'Segerön', precio: 200, descripcion: 'Crea una zona para comer y descansar en tu balcón, patio o terraza. La serie de muebles de exterior SEGERÖN es versátil y se ha diseñado especialmente para la vida en el exterior, así como para todo tipo de actividades al aire libre.', categoria: 'Jardin', imagen: 'https://www.ikea.com/es/es/images/products/segeron-mesa-jardin-verde-oscuro-gris-claro__1185545_pe898438_s5.jpg?f=xxs'},
    {nombre: 'Tegelön', precio: 349, descripcion: 'No te pierdas la oportunidad de organizar fiestas informales al aire libre. Esta mesa tiene capacidad de sobra para 4 personas y está hecha de diversos materiales que combinan estilo, ligereza y durabilidad.', categoria: 'Jardin', imagen: 'https://www.ikea.com/es/es/images/products/tegelon-mesa-jardin-gris-oscuro-negro__1082545_pe858701_s5.jpg?f=xxs'},
];
export const escritorio=[
    {nombre: 'Micke', precio: 79.99, descripcion: 'Un look de líneas sencillas que queda bien en cualquier parte. Se puede combinar con otros escritorios o módulos de cajones de la serie MICKE para tener más espacio de trabajo. El práctico diseño de la parte posterior permite ocultar los cables.', categoria: 'Estudio', imagen: 'https://www.ikea.com/es/es/images/products/micke-escritorio-antracita-rojo__0921882_pe787985_s5.jpg?f=xs'},
    {nombre: 'Torald', precio: 24.99, descripcion: '¿Necesitas un escritorio para un espacio reducido? Entonces el escritorio TORALD es lo que buscas. Ocupa un espacio mínimo en la habitación y, al mismo tiempo, es un lugar práctico para estudiar, dibujar y practicar hobbies.', categoria: 'Estudio', imagen: 'https://www.ikea.com/es/es/images/products/torald-escritorio-blanco__1055403_pe847976_s5.jpg?f=xs'},
    {nombre: 'Kallax', precio: 54.99, descripcion: 'Escritorio estrecho con un estilo atemporal y un práctico diseño bajo el tablero que te permite ocultar los cables. Puedes personalizarlo fácilmente añadiendo una puerta, cajas o accesorios de la serie KALLAX.', categoria: 'Estudio', imagen: 'https://www.ikea.com/es/es/images/products/kallax-escritorio-tinte-blanco-efecto-roble__1327542_pe944489_s5.jpg?f=xs'},
    {nombre: 'Kjellarne', precio: 119, descripcion: 'Este escritorio en forma de L ofrece mucho espacio para organizarte y mantenerlo todo a tu alcance. Así, podrás concentrarte en dibujar, crear, construir o hacer realidad tus ideas.', categoria: 'Estudio', imagen: 'https://www.ikea.com/es/es/images/products/kjellarne-escritorio-esquina-blanco__1433273_pe983192_s5.jpg?f=xs'},
    {nombre: 'Malm', precio: 179, descripcion: 'Un diseño de líneas sencillas y bonito se mire por donde se mire. Puedes ponerlo en el centro de la habitación o contra una pared, ya que los cables quedan ocultos. Coloca otra superficie de trabajo extraíble en el lateral izquierdo o derecho.', categoria: 'Estudio', imagen: 'https://www.ikea.com/es/es/images/products/malm-escritorio-con-tablero-extraible-blanco__0735980_pe740314_s5.jpg?f=xs'},
    {nombre: 'Alex', precio: 139, descripcion: 'El escritorio ALEX combina almacenaje práctico y diseño elegante. Te encantarán los cajones integrados, el amplio tablero y la solución de gestión de cables. Su estilo minimalista permite ponerlo en cualquier sitio, por lo que ofrece mucha funcionalidad.', categoria: 'Estudio', imagen: 'https://www.ikea.com/es/es/images/products/alex-escritorio-tinte-blanco-efecto-roble__0977670_pe813730_s5.jpg?f=xs'},
    {nombre: 'Tonstad', precio: 159, descripcion: 'Puedes usar este escritorio estrecho en blanco para tus aficiones, como tocador o como una elegante mesa para el recibidor. El diseño clásico y el acabado elegante confieren calidad a los muebles de la serie TONSTAD en color hueso.', categoria: 'Estudio', imagen: 'https://www.ikea.com/es/es/images/products/tonstad-escritorio-marron-chapa-roble-tenida__1329843_pe945273_s5.jpg?f=xs'},
    {nombre: 'Lisabo', precio: 169, descripcion: 'Estamos muy orgullosos de nuestra serie LISABO, que ha ganado el prestigioso premio internacional Red Dot Award por su diseño. Los productos que incluye son resistentes, duraderos y fáciles de montar, y ofrecen un aspecto ligero y artesanal.', categoria: 'Estudio', imagen: 'https://www.ikea.com/es/es/images/products/lisabo-escritorio-chapa-fresno__0735972_pe740306_s5.jpg?f=xs'},
];
export const armario=[
    {nombre: 'Kleppstad', precio: 79.99, descripcion: 'Sencillo y práctico. Un armario que ofrece todas las funciones básicas. Y si te falta espacio de almacenaje, puedes añadir otro armario de la serie KLEPPSTAD.', categoria: 'Dormitorio', imagen: 'https://www.ikea.com/es/es/images/products/kleppstad-armario-con-2-puertas-blanco__0733324_pe748781_s5.jpg?f=xs'},
    {nombre: 'Brimnes', precio: 99.99, descripcion: 'Los espacios reducidos requieren soluciones de almacenaje inteligentes. Este armario tiene una barra para colgar camisas y vestidos, un estante interior para colocar prendas dobladas, como camisetas y jerséis, y espacio para colgar prendas largas.', categoria: 'Dormitorio', imagen: 'https://www.ikea.com/es/es/images/products/brimnes-armario-con-2-puertas-blanco__0746968_pe744294_s5.jpg?f=xs'},
    {nombre: 'Metod', precio: 75, descripcion: 'El sistema de cocina METOD te ayuda a diseñar la cocina de tus sueños por dentro y por fuera. Si necesitas una solución para aprovechar una esquina, este armario te permite crear una cocina en forma de L o U.', categoria: 'Cocina', imagen: 'https://www.ikea.com/es/es/images/products/metod-armario-bajo-esquina-negro-gris__1386790_pe963954_s5.jpg?f=xs'},
    {nombre: 'Visthus', precio: 199, descripcion: 'Las patas regulables permiten corregir posibles desniveles en el suelo.', categoria: 'Dormitorio', imagen: 'https://www.ikea.com/es/es/images/products/visthus-armario-gris-blanco__0592300_pe674449_s5.jpg?f=xs'},
    {nombre: 'Lastare', precio: 249, descripcion: 'Con la herramienta de planificación LASTARE, es fácil crear una solución personalizada según tus gustos, tu hogar y tus necesidades de almacenaje.', categoria: 'Dormitorio', imagen: 'https://www.ikea.com/es/es/images/products/lastare-combinacion-armario-blanco__1472949_pe997626_s5.jpg?f=xs'},
    {nombre: 'Smästad', precio: 136, descripcion: 'Este armario es pequeño pero engañoso; cabe de todo: desde ropa para bebé hasta vaqueros de adolescente. En las barras para la ropa hay espacio para perchas, en las que tu hijo podrá colgar su ropa por su cuenta.', categoria: 'Dormitorio', imagen: 'https://www.ikea.com/es/es/images/products/smastad-platsa-armario-blanco-azul-con-2-barras-armario__1242796_pe920399_s5.jpg?f=xs'},
    {nombre: 'Smagöra', precio: 139, descripcion: 'Cuando creamos la serie tradicional SMÅGÖRA nos concentramos en la seguridad. Por eso todas las superficies de la cuna, el cambiador y el armario son no tóxicas y los bordes y esquinas están redondeados.', categoria: 'Dormitorio', imagen: 'https://www.ikea.com/es/es/images/products/smagora-armario-blanco__0774692_pe756737_s5.jpg?f=xs'},
    {nombre: 'Sundvik', precio: 249, descripcion: 'Estilo atemporal, materiales duraderos y detalles cuidados para este armario con bastante fondo que seguirá a tu hijo desde la niñez hasta la edad adulta.', categoria: 'Dormitorio', imagen: 'https://www.ikea.com/es/es/images/products/sundvik-armario-blanco__0917896_ph168402_s5.jpg?f=xs'},
];
export const inodoro=[
    {nombre: 'Valloxen', precio: 19.99, descripcion: 'Las bisagras con tope integrado paran el asiento del váter y lo cierran de manera suave, lenta y silenciosa.', categoria: 'Baño', imagen: 'https://www.ikea.com/es/es/images/products/valloxen-asiento-inodoro-blanco__0863685_pe699545_s5.jpg?f=xs'},
    {nombre: 'Kullarna', precio: 39.99, descripcion: 'Cambiar el asiento del inodoro es la manera perfecta de renovar el baño sin tener que comprar uno nuevo. Este se cierra de manera suave y lenta para que nada perturbe el ambiente apacible.', categoria: 'Baño', imagen: 'https://www.ikea.com/es/es/images/products/kullarna-asiento-inodoro-blanco__0757763_pe749406_s5.jpg?f=xs'},
    {nombre: 'Tossig', precio: 5.99, descripcion: 'Este asiento facilita a tu hijo el proceso de aprender a ir al baño. Con su forma y sus bordes redondeados, es ideal para culitos pequeños y resulta muy fácil de quitar y limpiar. Cuando no lo uses, puedes colgarlo de la pared o ponerlo a un lado.', categoria: 'Baño', imagen: 'https://www.ikea.com/es/es/images/products/tossig-asiento-inodoro-blanco-turquesa__1406321_pe970827_s5.jpg?f=xs'},
    {nombre: 'Ona', precio: 1929.95, descripcion: 'In-Wash® Ona - Smart toilet compacto adosado a pared Roca Rimless® con funciones de lavado y secado', categoria: 'Baño', imagen: 'https://www.roca.es/RocaResourceServlet/resources/getTransformation?idObject=4753d2bb85535eb4e09e9ad4f48e35ca&trName=TF_Mob_prod_xxl_v2'},
    {nombre: 'Avant', precio: 833.69, descripcion: 'E- Inodoro suspendido con cisterna integrada In-Tank®. Necesita toma eléctrica.', categoria: 'Baño', imagen: 'https://www.roca.es/RocaResourceServlet/resources/getTransformation?idObject=bb70c903657e5f594c9bee314ce96435&trName=TF_Mob_prod_xxl_v2'},
    {nombre: 'Tura', precio: 533.61, descripcion: 'Inodoro completo Roca Rimless® adosado a pared con salida dual (incluye taza y tapa amortiguada)', categoria: 'Baño', imagen: 'https://www.roca.es/RocaResourceServlet/resources/getTransformation?idObject=f305a5ebea42512b76b3b770152ec8a9&trName=TF_Mob_prod_xxl_v2'},
    {nombre: 'The Gap', precio: 405.35, descripcion: 'Square - Inodoro suspendido con salida horizontal y fijaciones ocultas (incluye taza Roca Rimless® y tapa amortiguada de Supralit®', categoria: 'Baño', imagen: 'https://www.roca.es/RocaResourceServlet/resources/getTransformation?idObject=%7BE0E8D0C9-2065-4989-80A4-48212B0B116C%7D&trName=TF_Mob_prod_xxl_v2'},
    {nombre: 'Avant', precio: 833.69, descripcion: 'E- Inodoro suspendido con cisterna integrada In-Tank®. Necesita toma eléctrica.', categoria: 'Baño', imagen: 'https://www.roca.es/RocaResourceServlet/resources/getTransformation?idObject=bb70c903657e5f594c9bee314ce96435&trName=TF_Mob_prod_xxl_v2'},
];
export const encimera=[
    {nombre: '', precio: 0, descripcion: '', categoria: '', imagen: ''},
    {nombre: '', precio: 0, descripcion: '', categoria: '', imagen: ''},
    {nombre: '', precio: 0, descripcion: '', categoria: '', imagen: ''},
    {nombre: '', precio: 0, descripcion: '', categoria: '', imagen: ''},
    {nombre: '', precio: 0, descripcion: '', categoria: '', imagen: ''},
    {nombre: '', precio: 0, descripcion: '', categoria: '', imagen: ''},
    {nombre: '', precio: 0, descripcion: '', categoria: '', imagen: ''},
    {nombre: '', precio: 0, descripcion: '', categoria: '', imagen: ''},
];
export const estanteria=[
    {nombre: '', precio: 0, descripcion: '', categoria: '', imagen: ''},
    {nombre: '', precio: 0, descripcion: '', categoria: '', imagen: ''},
    {nombre: '', precio: 0, descripcion: '', categoria: '', imagen: ''},
    {nombre: '', precio: 0, descripcion: '', categoria: '', imagen: ''},
    {nombre: '', precio: 0, descripcion: '', categoria: '', imagen: ''},
    {nombre: '', precio: 0, descripcion: '', categoria: '', imagen: ''},
    {nombre: '', precio: 0, descripcion: '', categoria: '', imagen: ''},
    {nombre: '', precio: 0, descripcion: '', categoria: '', imagen: ''},
];
export const perchero=[
    {nombre: '', precio: 0, descripcion: '', categoria: '', imagen: ''},
    {nombre: '', precio: 0, descripcion: '', categoria: '', imagen: ''},
    {nombre: '', precio: 0, descripcion: '', categoria: '', imagen: ''},
    {nombre: '', precio: 0, descripcion: '', categoria: '', imagen: ''},
    {nombre: '', precio: 0, descripcion: '', categoria: '', imagen: ''},
    {nombre: '', precio: 0, descripcion: '', categoria: '', imagen: ''},
    {nombre: '', precio: 0, descripcion: '', categoria: '', imagen: ''},
    {nombre: '', precio: 0, descripcion: '', categoria: '', imagen: ''},
];